# Generated by Django 5.2.4 on 2025-07-15 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_folder_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="article",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="user",
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("tech", "技术"), ("literature", "文学"), ("life", "生活")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
