# Generated by Django 5.2.4 on 2025-07-15 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_remove_article_folder_remove_article_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_favorite",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("tech", "技术"), ("life", "生活"), ("other", "其他")],
                default="tech",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
