# Generated by Django 5.2.4 on 2025-07-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_remove_article_is_favorite_remove_article_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
