# Generated by Django 5.2.4 on 2025-07-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0006_alter_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(max_length=20),
        ),
    ]
